# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  default:
    external:
      name: my-net
#networks:
  #my-net:

services:
    peer1.org1.example.com:
        container_name: peer1.org1.example.com
        image: hyperledger/fabric-peer
        environment:
          - CORE_PEER_ID=peer1.org1.example.com
          - CORE_PEER_PROFILE_ENABLED=true
          - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer.example.com:7050
          - CORE_PEER_GOSSIP_IGNORESECURITY=true
          - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
          - CORE_PEER_TLS_ENABLED=false
          - CORE_PEER_GOSSIP_USELEADERELECTION=false
          - CORE_PEER_GOSSIP_ORGLEADER=true
          - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
          - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
          - CORE_PEER_LOCALMSPID=Org1MSP
          - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.example.com:9443
          - CORE_METRICS_PROVIDER=prometheus
          - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
          - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
          - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME= 
          - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD= 
          - CORE_PEER_ADDRESSAUTODETECT=true
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - CORE_LOGGING_LEVEL=DEBUG
          - CORE_PEER_NETWORKID=peer1.org1.example.com
          - CORE_NEXT=true
          - CORE_PEER_ENDORSER_ENABLED=true
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
        ports:
          - 9051:7051
          - 9053:7053
        #networks:
          #- my-net
        external_links:
          - orderer.example.com:orderer.example.com 
          - peer0.org1.example.com:peer0.org1.example.com