# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  default:
    external:
      name: my-net


services:
    couchdb2:
        container_name: couchdb2
        image: hyperledger/fabric-couchdb
        # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
        # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
        environment:
          - COUCHDB_USER=
          - COUCHDB_PASSWORD=
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
          - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
        ports:
          - "7984:5984"
    peer2.org1.example.com:
        container_name: peer2.org1.example.com
        image: hyperledger/fabric-peer
        environment:
          - CORE_PEER_ID=peer2.org1.example.com
          - CORE_PEER_PROFILE_ENABLED=true
          - CORE_PEER_COMMITTER_LEDGER_ORDERER=orderer.example.com:7050
          - CORE_PEER_GOSSIP_IGNORESECURITY=true
          - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=my-net
          - CORE_PEER_TLS_ENABLED=false
          - CORE_PEER_GOSSIP_USELEADERELECTION=false
          - CORE_PEER_GOSSIP_ORGLEADER=true
          - CORE_PEER_LOCALMSPID=Org1MSP
          - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
          - CORE_OPERATIONS_LISTENADDRESS=peer2.org1.example.com:9443
          - CORE_METRICS_PROVIDER=prometheus
          - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
          - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
          - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME= 
          - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD= 
          - CORE_PEER_ADDRESSAUTODETECT=true
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - CORE_LOGGING_LEVEL=DEBUG
          - CORE_PEER_NETWORKID=peer2.org1.example.com
          - CORE_NEXT=true
          - CORE_PEER_ENDORSER_ENABLED=true
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: peer node start
        volumes:
            - /var/run/:/host/var/run/
            - ./crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp:/etc/hyperledger/fabric/msp
        ports:
          - 10051:7051
          - 10053:7053
        external_links:
          - orderer.example.com:orderer.example.com 
          - peer0.org1.example.com:peer0.org1.example.com
        depends_on:
          - couchdb2